import type { CampaignMetric, DailyMetric, Project, Recommendation, SyncLog } from "@/types";

export const projects: Project[] = [
  {
    id: "ks-otdelka-pomeshcheniy",
    name: "КС. Отделка помещений",
    slug: "ks-otdelka-pomeshcheniy",
    status: "stale",
    color: "#2563eb",
    description: "Реклама услуг по отделке помещений",
    vkProfile: "ks",
    vkAccountId: "1090883679",
    connectionType: "api",
    targetCpl: 900,
    dailyBudget: 1667,
    monthlyBudget: 50000,
    primaryConversion: "Сообщения",
    kpi1: "50 000 ₽ в месяц",
    kpi2: "900 ₽ за сообщение / 2 000 ₽ за лид",
    kpi3: "500 ₽ за сообщение / 1 500 ₽ за лид",
    lastSyncStatus: "pending",
  },
  {
    id: "quarta",
    name: "Quarta",
    slug: "quarta",
    status: "stale",
    color: "#f59e0b",
    description: "Рекламный проект Quarta",
    vkProfile: "quarta",
    vkAccountId: "30737452",
    connectionType: "api",
    targetCpl: 30,
    dailyBudget: 3000,
    monthlyBudget: 90000,
    primaryConversion: "Подписки",
    kpi1: "90 000 ₽ в месяц",
    kpi2: "Подписчик до 30 ₽",
    kpi3: "Сообщение в сообщество до 200 ₽",
    lastSyncStatus: "pending",
  },
  {
    id: "hut",
    name: "HUT",
    slug: "hut",
    status: "stale",
    color: "#10b981",
    description: "Рекламный проект HUT",
    vkProfile: "hut",
    vkAccountId: "30615001",
    connectionType: "api",
    targetCpl: 30,
    dailyBudget: 3000,
    monthlyBudget: 90000,
    primaryConversion: "Подписки",
    kpi1: "90 000 ₽ в месяц",
    kpi2: "Подписчик до 30 ₽",
    kpi3: "Сообщение в сообщество до 200 ₽",
    lastSyncStatus: "pending",
  },
  {
    id: "emalis",
    name: "Эмалис",
    slug: "emalis",
    status: "stale",
    color: "#ec4899",
    description: "Рекламный проект Эмалис",
    vkProfile: "emalis",
    vkAccountId: "29867480",
    connectionType: "api",
    targetCpl: 400,
    dailyBudget: 2667,
    monthlyBudget: 80000,
    primaryConversion: "Сообщения",
    kpi1: "80 000 ₽ в месяц, с НДС",
    kpi2: "400 ₽ за сообщение",
    kpi3: "600 ₽ за сообщение",
    lastSyncStatus: "pending",
  },
  {
    id: "globus",
    name: "Глобус",
    slug: "globus",
    status: "stale",
    color: "#8b5cf6",
    description: "Рекламный проект Глобус",
    vkProfile: "globus",
    vkAccountId: "24085087",
    connectionType: "api",
    targetCpl: 250,
    dailyBudget: 780,
    monthlyBudget: 23400,
    primaryConversion: "Заявки",
    kpi1: "23 400 ₽ в месяц",
    kpi2: "30 заявок с датами и количеством гостей",
    kpi3: "250 ₽ по кабинету",
    lastSyncStatus: "pending",
  },
  {
    id: "gorki-golf",
    name: "Горки Гольф",
    slug: "gorki-golf",
    status: "stale",
    color: "#14b8a6",
    description: "Рекламный проект Горки Гольф",
    vkProfile: "gorki_golf",
    vkAccountId: "30638565",
    connectionType: "api",
    targetCpl: 400,
    dailyBudget: 1170,
    monthlyBudget: 35100,
    primaryConversion: "Сообщения",
    kpi1: "35 100 ₽ в месяц",
    kpi2: "30 заявок с датами и количеством гостей",
    kpi3: "400 ₽ за сообщение",
    lastSyncStatus: "pending",
  },
  {
    id: "klyuchi",
    name: "Отделка балконов",
    slug: "klyuchi",
    status: "stale",
    color: "#f59e0b",
    description: "Рекламный проект «Отделка балконов»",
    vkProfile: "klyuchi",
    vkAccountId: "1090653047",
    connectionType: "api",
    targetCpl: 1000,
    dailyBudget: 3333,
    monthlyBudget: 100000,
    primaryConversion: "Заявки",
    kpi1: "100 000 ₽ в месяц",
    kpi2: "Заявка до 1 000 ₽",
    kpi3: "Целевой замер до 10 000 ₽",
    lastSyncStatus: "pending",
  },
  {
    id: "russian-height",
    name: "Русская высота",
    slug: "russian-height",
    status: "stale",
    color: "#06b6d4",
    description: "Рекламный проект «Русская высота»",
    vkProfile: "russian_height",
    vkAccountId: "26197615",
    connectionType: "api",
    targetCpl: 1000,
    dailyBudget: 3333,
    monthlyBudget: 100000,
    primaryConversion: "Замеры",
    kpi1: "100 000 ₽ в месяц",
    kpi2: "8 замеров",
    kpi3: "Заявка до 1 000 ₽ по кабинету",
    lastSyncStatus: "pending",
  },
  {
    id: "hevva",
    name: "HEVVA",
    slug: "hevva",
    status: "stale",
    color: "#a855f7",
    description: "Рекламный проект HEVVA",
    vkProfile: "hevva",
    vkAccountId: "28892096",
    connectionType: "api",
    targetCpl: 300,
    dailyBudget: 1667,
    monthlyBudget: 50000,
    primaryConversion: "Сообщения",
    kpi1: "50 000 ₽ в месяц",
    kpi2: "300 ₽ за сообщение",
    kpi3: "500 ₽ за сообщение",
    lastSyncStatus: "pending",
  },
  {
    id: "skazochny-bor",
    name: "Сказочный бор",
    slug: "skazochny-bor",
    status: "stale",
    color: "#22c55e",
    description: "Рекламный проект «Сказочный бор»",
    vkProfile: "skazochny_bor",
    vkAccountId: "1090464582",
    connectionType: "api",
    targetCpl: 72,
    dailyBudget: 1560,
    monthlyBudget: 46800,
    primaryConversion: "Подписчики",
    kpi1: "46 800 ₽ в месяц",
    kpi2: "Подписчик до 72 ₽",
    kpi3: "250 ₽ за сообщение",
    lastSyncStatus: "pending",
  },
];

export const projectSummaries: Record<string, {
  yesterday: number;
  month: number;
  results: number;
  cpl: number;
  change: number;
}> = {};

export const daily: DailyMetric[] = [];
export const campaigns: CampaignMetric[] = [];
export const recommendations: Recommendation[] = [];
export const syncLogs: SyncLog[] = [];
